api:
  build: api
  ports:
    - "3000:3000"
nginx:
  build: nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - api
redis:
  image: redis:latest
  command: redis-server --appendonly yes
  volumes:
    - ./data:/data
hubot:
  build: hubot
  links:
    - redis
